apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: 654654346698.dkr.ecr.ap-northeast-2.amazonaws.com/ticketping/react-app:latest
          env:
            - name: REACT_APP_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: react-env-config
                  key: REACT_APP_API_HOST
            - name: REACT_APP_TOSS_CLIENT_KEY
              valueFrom:
                configMapKeyRef:
                  name: react-env-config
                  key: REACT_APP_TOSS_CLIENT_KEY                     